version: "3.1"
#Indicamos la version docker compose que utilizamos
#Y luego los servicios que vamos a implementar
services:
    db:
        image: mysql:5.7.38
        container_name: DBServer
        ports: 
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            #Base de Datos que utilizaremos.
            MYSQL_DATABASE: app_escolar
            # Contraseña para root
            MYSQL_ROOT_PASSWORD: pass
        volumes:
            - .db:/docker-entrypoint_initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    www:
        build:
           #Indicamos la carpeta donde guardamos el Docker File
          #context: ./docker_file
           #Indicamos el archivo dockerfile de este contenedor
          dockerfile: dockerfile
        ports: 
            - 9091:80
        volumes:
             #Carpeta donde guardaremos los archivos web : carpeta interna de Docker
            - ./pagina:/var/www/html
        links:
             #Indicamos con quien va relacionado
            - db
        networks:
            - default
        container_name: WebServer
    phpmyadmin: 
        image: phpmyadmin:5.1
        container_name: PHPMyAdmin
        links: 
            #Indicamos con quien va relacionado
            - db:db
        ports:
            - 8081:80
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: pass
volumes:
    persistent:
